import type { DefaultSound } from "./config";

export const defaultFilterSounds: DefaultSound[] = [
  {
    displayName: "1",
    id: "AlertSound1",
    path: "static/sounds/AlertSound1.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "2",
    id: "AlertSound2",
    path: "static/sounds/AlertSound2.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "3",
    id: "AlertSound3",
    path: "static/sounds/AlertSound3.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "4",
    id: "AlertSound4",
    path: "static/sounds/AlertSound4.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "5",
    id: "AlertSound5",
    path: "static/sounds/AlertSound5.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "6",
    id: "AlertSound6",
    path: "static/sounds/AlertSound6.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "7",
    id: "AlertSound7",
    path: "static/sounds/AlertSound7.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "8",
    id: "AlertSound8",
    path: "static/sounds/AlertSound8.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "9",
    id: "AlertSound9",
    path: "static/sounds/AlertSound9.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "10",
    id: "AlertSound10",
    path: "static/sounds/AlertSound10.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "11",
    id: "AlertSound11",
    path: "static/sounds/AlertSound11.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "12",
    id: "AlertSound12",
    path: "static/sounds/AlertSound12.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "13",
    id: "AlertSound13",
    path: "static/sounds/AlertSound13.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "14",
    id: "AlertSound14",
    path: "static/sounds/AlertSound14.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "15",
    id: "AlertSound15",
    path: "static/sounds/AlertSound15.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "16",
    id: "AlertSound16",
    path: "static/sounds/AlertSound16.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "Alchemy",
    id: "AlertSoundShAlchemy",
    path: "static/sounds/AlertSoundShAlchemy.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "Blessed",
    id: "AlertSoundShBlessed",
    path: "static/sounds/AlertSoundShBlessed.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "Chaos",
    id: "AlertSoundShChaos",
    path: "static/sounds/AlertSoundShChaos.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "Divine",
    id: "AlertSoundShDivine",
    path: "static/sounds/AlertSoundShDivine.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "Exalted",
    id: "AlertSoundShExalted",
    path: "static/sounds/AlertSoundShExalted.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "Fusing",
    id: "AlertSoundShFusing",
    path: "static/sounds/AlertSoundShFusing.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "General",
    id: "AlertSoundShGeneral",
    path: "static/sounds/AlertSoundShGeneral.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "Mirror",
    id: "AlertSoundShMirror",
    path: "static/sounds/AlertSoundShMirror.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "Regal",
    id: "AlertSoundShRegal",
    path: "static/sounds/AlertSoundShRegal.mp3",
    type: "default",
    data: null,
  },
  {
    displayName: "Vaal",
    id: "AlertSoundShVaal",
    path: "static/sounds/AlertSoundShVaal.mp3",
    type: "default",
    data: null,
  },
];
